{{- if eq .Values.cloudprovider "cloudstack" }}
{{- range $index, $nodepool := .Values.nodepools }}
apiVersion: rke-machine-config.cattle.io/v1
kind: CloudstackConfig
metadata:
  name: {{ $nodepool.name }}
  namespace: fleet-default
common:
{{- if $nodepool.labels }}
  labels:
{{ toYaml $nodepool.labels | indent 4 }}
{{- end }}
{{- if $nodepool.taints }}
  taints:
{{ toYaml $nodepool.taints | indent 4 }}
{{- end }}
backups: {{ $nodepool.backups }}
template: {{ $nodepool.template }}
#ipv6: {{ $nodepool.ipv6 }}
monitoring: {{ $nodepool.monitoring }}
usePrivateAddress: {{ $nodepool.usePrivateAddress }}
expunge: {{ $nodepool.expunge }}
apiUrl: {{ $nodepool.apiUrl }}
zone: {{ $nodepool.zone }}
serviceOffering: {{ $nodepool.serviceOffering }}
#sshKeyContents: {{ $nodepool.sshKeyContents }}
#sshKeyFingerprint: {{ $nodepool.sshKeyFingerprint }}
sshPort: {{ $nodepool.sshPort | quote }}
sshUser: {{ $nodepool.sshUser }}
tags: {{ $nodepool.tags }}
userdata: {{ $nodepool.userdata }}
---
{{- end }}
{{ $nodepool := .Values.nodepool }}
{{- if $nodepool }}
apiVersion: rke-machine-config.cattle.io/v1
kind: CloudstackConfig
metadata:
  name: {{ $nodepool.name }}
  namespace: fleet-default
common:
{{- if $nodepool.labels }}
  labels:
{{ toYaml $nodepool.labels | indent 4 }}
{{- end }}
{{- if $nodepool.taints }}
  taints:
{{ toYaml $nodepool.taints | indent 4 }}
{{- end }}
backups: {{ $nodepool.backups }}
template: {{ $nodepool.template }}
#ipv6: {{ $nodepool.ipv6 }}
monitoring: {{ $nodepool.monitoring }}
usePrivateAddress: {{ $nodepool.usePrivateAddress }}
expunge: {{ $nodepool.expunge }}
apiUrl: {{ $nodepool.apiUrl }}
zone: {{ $nodepool.zone }}
serviceOffering: {{ $nodepool.serviceOffering }}
#sshKeyContents: {{ $nodepool.sshKeyContents }}
#sshKeyFingerprint: {{ $nodepool.sshKeyFingerprint }}
sshPort: {{ $nodepool.sshPort | quote }}
sshUser: {{ $nodepool.sshUser }}
#tags: {{ $nodepool.tags }}
userdata: {{ $nodepool.userdata }}
{{- end }}
{{- end }}
